DROP TABLE headers;
DROP TABLE bodies;
DROP TABLE receipts;
DROP TABLE accounts;
DROP TABLE rewards;
DROP TABLE internal_transactions;
DROP TABLE pending_transactions;
DROP TABLE chain_splits;
DROP TABLE reorgs;
